
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('skill').del()
    .then(function () {
      // Inserts seed entries
      return knex('skill').insert([
        {name: 'JavaScript', type: "TECH"},
        {name: 'Java', type: "TECH"},
        {name: 'C++', type: "TECH"},
        {name: 'CSS', type: "TECH"},
        {name: 'PHP', type: "TECH"},
        {name: 'NPM', type: "TECH"},
        {name: 'Python', type: "TECH"},
        {name: 'TypeScript', type: "TECH"},
        {name: 'Vim', type: "TECH"},
        {name: 'GitHub', type: "TECH"},
        {name: 'Docker', type: "TECH"},
        {name: 'Jenkins', type: "TECH"},
        {name: 'Flutter', type: "TECH"},
        {name: 'Vue.js', type: "TECH"},
        {name: 'Angular.js', type: "TECH"},
        {name: 'React.js', type: "TECH"},
        {name: 'Time Management', type: "SOFT"},
        {name: 'Team Management', type: "SOFT"},
        {name: 'Communications', type: "SOFT"},
        {name: 'Project Management', type: "SOFT"},
        {name: 'Public Speaking', type: "SOFT"},
        {name: 'Anger Management', type: "SOFT"},
        {name: 'Problem-solving', type: "SOFT"},
        {name: 'Care for details', type: "SOFT"},
        {name: 'Punctuality', type: "SOFT"},
        {name: 'Open mindness', type: "SOFT"},
        {name: 'Flexibility', type: "SOFT"},
        {name: 'C#', type: "TECH"},
        {name: 'Visual Basic', type: "TECH"},
        {name: 'R', type: "TECH"},
        {name: 'Groovy', type: "TECH"},
        {name: 'Assembly language', type: "TECH"},
        {name: 'SQL', type: "TECH"},
        {name: 'Swift', type: "TECH"},
        {name: 'Go', type: "TECH"},
        {name: 'Ruby', type: "TECH"},
        {name: 'MATLAB', type: "TECH"},
        {name: 'Perl', type: "TECH"},
        {name: 'Objective-C', type: "TECH"},
        {name: 'Delphi/Object Pascal', type: "TECH"},
        {name: 'Classic Visual Basic', type: "TECH"},
        {name: 'SAS', type: "TECH"},
        {name: 'PL/SQL', type: "TECH"},
        {name: 'Julia', type: "TECH"},
        {name: 'Scratch', type: "TECH"},
        {name: 'Dart', type: "TECH"},
        {name: 'Rust', type: "TECH"},
        {name: 'ABAP', type: "TECH"},
        {name: 'JSON', type: "TECH"},
        {name: 'YAML', type: "TECH"},
        {name: 'Fortran', type: "TECH"},
        {name: 'COBOL', type: "TECH"},
        {name: 'Ada', type: "TECH"},
        {name: 'Transact-SQL', type: "TECH"},
        {name: 'Scala', type: "TECH"},
        {name: 'VHDL', type: "TECH"},
        {name: 'Lisp', type: "TECH"},
        {name: 'Lua', type: "TECH"},
        {name: 'PowerShell', type: "TECH"},
        {name: '(Visual) FoxPro', type: "TECH"},
        {name: 'Kotlin', type: "TECH"},
        {name: 'Logo', type: "TECH"},
        {name: 'LabVIEW', type: "TECH"},
        {name: 'Haskell', type: "TECH"},
        {name: 'Apex', type: "TECH"},
        {name: 'Bash', type: "TECH"},
        {name: 'Awk', type: "TECH"},
        {name: 'Solidity', type: "TECH"},
        {name: 'Scheme', type: "TECH"},
        {name: 'VBScript', type: "TECH"},
        {name: 'Google Suite', type: "TECH"},
        {name: 'Trello', type: "TECH"},
        {name: 'Slack', type: "TECH"},
        {name: 'Zapier', type: "TECH"},
        {name: 'Zoom', type: "TECH"},
        {name: 'JIRA', type: "TECH"},
        {name: 'Salesforce', type: "TECH"},
        {name: 'Microsoft Office', type: "TECH"},
        {name: 'Budget planning', type: "TECH"},
        {name: 'Risk management', type: "TECH"},
        {name: 'Project planning', type: "TECH"},
        {name: 'PM tools', type: "TECH"},
        {name: 'Task management', type: "TECH"},
        {name: 'SCRUM methodology', type: "TECH"},
        {name: 'Agile methodology', type: "TECH"},
        {name: 'Product roadmaps', type: "TECH"},
        {name: 'User experience design', type: "TECH"},
        {name: 'Programming skills', type: "TECH"},
        {name: 'Product lifecycle management', type: "TECH"},
        {name: 'QA testing', type: "TECH"},
        {name: 'Requirements gathering', type: "TECH"},
        {name: 'Coding', type: "TECH"},
        {name: 'Debugging', type: "TECH"},
        {name: 'Implementation', type: "TECH"},
        {name: 'Testing', type: "TECH"},
        {name: 'Design', type: "TECH"},
        {name: 'Configuration', type: "TECH"},
        {name: 'Applications', type: "TECH"},
        {name: 'IOS', type: "TECH"},
        {name: 'Android', type: "TECH"},
        {name: 'Cross-platform mobile', type: "TECH"},
        {name: 'Client-side Web', type: "TECH"},
        {name: 'Server-side Web', type: "TECH"},
        {name: 'Embedded systems', type: "TECH"},
        {name: 'Streaming platforms', type: "TECH"},
        {name: 'Messaging queues', type: "TECH"},
        {name: 'MySQL', type: "TECH"},
        {name: 'PostgresSQL', type: "TECH"},
        {name: 'Microsoft SQL', type: "TECH"},
        {name: 'MongoDB', type: "TECH"},
        {name: 'NOSQL', type: "TECH"},
        {name: 'Spatial', type: "TECH"},
        {name: 'Time series databases', type: "TECH"},
        {name: 'ER (database design)', type: "TECH"},
        {name: 'UML', type: "TECH"},
        {name: 'Microsoft Visio', type: "TECH"},
        {name: 'JQuery', type: "TECH"},
        {name: 'Node.js', type: "TECH"},
        {name: 'Ember.js', type: "TECH"},
        {name: 'Eclipse', type: "TECH"},
        {name: 'NetBeans', type: "TECH"},
        {name: 'Google Maps API', type: "TECH"},
        {name: 'Google Earth API', type: "TECH"},
        {name: 'Leaflet', type: "TECH"},
        {name: 'OpenStreetMap', type: "TECH"},
        {name: 'Hibernate', type: "TECH"},
        {name: 'Spring framework', type: "TECH"},
        {name: 'REST API development', type: "TECH"},
        {name: 'Web services development', type: "TECH"},
        {name: 'ElasticSearch', type: "TECH"},
        {name: 'Heroku', type: "TECH"},
        {name: 'OpenStack', type: "TECH"},
        {name: 'Azure', type: "TECH"},
        {name: 'Machine Learning', type: "TECH"},
        {name: 'Neural networks', type: "TECH"},
        {name: 'Low-level network programming', type: "TECH"},
        {name: 'Bluethoot communication', type: "TECH"},
        {name: 'NFC communication', type: "TECH"},
        {name: 'Augmented reality on mobile platforms', type: "TECH"},
        {name: 'Amazon Alexa skill development', type: "TECH"},
        {name: 'Google Assistant develpment', type: "TECH"},
        {name: 'Qt framework', type: "TECH"},
        {name: 'Skype', type: "TECH"},
        {name: 'Telegram', type: "TECH"},
        {name: 'Languages', type: "TECH"},
        {name: 'Security', type: "TECH"},
        {name: 'Algorithms', type: "TECH"},
        {name: 'Modeling', type: "TECH"},
        {name: 'Documentation', type: "TECH"},
        {name: 'Adobe creative apps', type: "TECH"},
        {name: 'HTML', type: "TECH"},
        {name: 'Interactive media', type: "TECH"},
        {name: 'Wireframing', type: "TECH"},
        {name: 'UX research', type: "TECH"},
        {name: 'Prototyping', type: "TECH"},
        {name: 'Color theory', type: "TECH"},
        {name: 'Responsive design', type: "TECH"},
        {name: 'Photoshop', type: "TECH"},
        {name: 'Sketch', type: "TECH"},
        {name: 'User modeling', type: "TECH"},
        {name: 'Search Engine Optimization', type: "TECH"},
        {name: 'Digital media', type: "TECH"},
        {name: 'Social media platforms', type: "TECH"},
        {name: 'Automated marketing software', type: "TECH"},
        {name: 'Content Management Systems', type: "TECH"},
        {name: 'Copywriting', type: "TECH"},
        {name: 'Content creation', type: "TECH"},
        {name: 'Google Analytics', type: "TECH"},
        {name: 'Marketing analytics tools', type: "TECH"},
        {name: 'Git', type: "TECH"},
        {name: 'Stack Overflow', type: "TECH"},
        {name: 'Docker', type: "TECH"},
        {name: 'Confluence', type: "TECH"},
        {name: 'Feedly', type: "TECH"},
        {name: 'Tmux', type: "TECH"},
        {name: 'Microsoft Windows', type: "TECH"},
        {name: 'Linux', type: "TECH"},
        {name: 'MacOS X', type: "TECH"},
        {name: 'The Code Project', type: "TECH"},
        {name: 'Chrome DevTools', type: "TECH"},
        {name: 'Sublime Text', type: "TECH"},
        {name: 'LaTeX', type: "TECH"},
        {name: 'Axosoft', type: "TECH"},
        {name: 'Pivotal Tracker', type: "TECH"},
        {name: 'Asana', type: "TECH"},
        {name: 'Binfire', type: "TECH"},
        {name: 'Clarity', type: "SOFT"},
        {name: 'Confidence', type: "SOFT"},
        {name: 'Respect', type: "SOFT"},
        {name: 'Empathy', type: "SOFT"},
        {name: 'Listening', type: "SOFT"},
        {name: 'Verbal communication', type: "SOFT"},
        {name: 'Non-verbal communication', type: "SOFT"},
        {name: 'Written communication', type: "SOFT"},
        {name: 'Constructive feedback', type: "SOFT"},
        {name: 'Friendliness', type: "SOFT"},
        {name: 'Clarity', type: "SOFT"},
        {name: 'Confidence', type: "SOFT"},
        {name: 'Respect', type: "SOFT"},
        {name: 'Empathy', type: "SOFT"},
        {name: 'Listening', type: "SOFT"},
        {name: 'Verbal communication', type: "SOFT"},
        {name: 'Non-verbal communication', type: "SOFT"},
        {name: 'Written communication', type: "SOFT"},
        {name: 'Constructive feedback', type: "SOFT"},
        {name: 'Friendliness', type: "SOFT"},
        {name: 'Curiosity', type: "SOFT"},
        {name: 'Self-management', type: "SOFT"},
        {name: 'Decision-making', type: "SOFT"},
        {name: 'Calmness', type: "SOFT"},
        {name: 'Optimism', type: "SOFT"},
        {name: 'Analysis', type: "SOFT"},
        {name: 'Self-confidence', type: "SOFT"},
        {name: 'Organization', type: "SOFT"},
        {name: 'Self-motivation', type: "SOFT"},
        {name: 'Analysis', type: "SOFT"},
        {name: 'Lateral thinking', type: "SOFT"},
        {name: 'Logical reasoning', type: "SOFT"},
        {name: 'Initiative', type: "SOFT"},
        {name: 'Persistence', type: "SOFT"},
        {name: 'Observation', type: "SOFT"},
        {name: 'Persuasion', type: "SOFT"},
        {name: 'Negotiation', type: "SOFT"},
        {name: 'Brainstorming', type: "SOFT"},
        {name: 'Decision making', type: "SOFT"},
        {name: 'Divergent thinking', type: "SOFT"},
        {name: 'Inspiration', type: "SOFT"},
        {name: 'Imagination', type: "SOFT"},
        {name: 'Reframing', type: "SOFT"},
        {name: 'Mind mapping', type: "SOFT"},
        {name: 'Insight', type: "SOFT"},
        {name: 'Innovation', type: "SOFT"},
        {name: 'Experimenting', type: "SOFT"},
        {name: 'Questioning', type: "SOFT"},
        {name: 'Design', type: "SOFT"},
        {name: 'Teamwork', type: "SOFT"},
        {name: 'Adaptability', type: "SOFT"},
        {name: 'Problem-Solving', type: "SOFT"},
        {name: 'Creativity', type: "SOFT"},
        {name: 'Integrity', type: "SOFT"},
        {name: 'Responsibility', type: "SOFT"},
        {name: 'Discipline', type: "SOFT"},
        {name: 'Initiative', type: "SOFT"},
        {name: 'Dependability', type: "SOFT"},
        {name: 'Commitment', type: "SOFT"},
        {name: 'Self-motivated', type: "SOFT"},
        {name: 'Professionalism', type: "SOFT"},
        {name: 'Teamwork', type: "SOFT"},
        {name: 'Time-management', type: "SOFT"},
        {name: 'Empathy', type: "SOFT"},
        {name: 'Humor', type: "SOFT"},
        {name: 'Mentoring', type: "SOFT"},
        {name: 'Networking', type: "SOFT"},
        {name: 'Sensitivity', type: "SOFT"},
        {name: 'Patience', type: "SOFT"},
        {name: 'Tolerance', type: "SOFT"},
        {name: 'Public speaking', type: "SOFT"},
        {name: 'Positive reinforcement', type: "SOFT"},
        {name: 'Diplomacy', type: "SOFT"},
        {name: 'Goal setting', type: "SOFT"},
        {name: 'Prioritizing', type: "SOFT"},
        {name: 'Self-starter', type: "SOFT"},
        {name: 'Planning', type: "SOFT"},
        {name: 'Decision making', type: "SOFT"},
        {name: 'Focus', type: "SOFT"},
        {name: 'Delegation', type: "SOFT"},
        {name: 'Stress management', type: "SOFT"},
        {name: 'Coping', type: "SOFT"},
        {name: 'Organization', type: "SOFT"},
        {name: 'Leadership', type: "SOFT"},
        {name: 'Project management', type: "SOFT"},
        {name: 'Empathy', type: "SOFT"},
        {name: 'Selflessness', type: "SOFT"},
        {name: 'Agility', type: "SOFT"},
        {name: 'Listening', type: "SOFT"},
        {name: 'Humility', type: "SOFT"},
        {name: 'Cultural intelligence', type: "SOFT"},
        {name: 'Authenticity', type: "SOFT"},
        {name: 'Versatility', type: "SOFT"},
        {name: 'Generosity', type: "SOFT"},
        {name: 'Trust', type: "SOFT"},
        {name: 'Critical observation', type: "SOFT"},
        {name: 'Listening', type: "SOFT"},
        {name: 'Organization', type: "SOFT"},
        {name: 'Scheduling', type: "SOFT"},
        {name: 'Analysis', type: "SOFT"},
        {name: 'Introspection', type: "SOFT"},
        {name: 'Memory', type: "SOFT"},
        {name: 'Acuity', type: "SOFT"},
        {name: 'Recall', type: "SOFT"},
        {name: 'Questioning', type: "SOFT"}
      ]);
    });
};
